# Generated by Django 4.2 on 2023-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientepf',
            name='rg',
            field=models.CharField(max_length=12),
        ),
    ]
