# Generated by Django 4.2 on 2023-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastBank', '0003_remove_emprestimo_observacao_emprestimo_valorpagar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='failed_login_attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tentativas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
