# Generated by Django 4.2 on 2023-06-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastBank', '0004_cliente_failed_login_attempts_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='tentativas',
        ),
    ]
