# Generated by Django 4.2 on 2023-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastBank', '0005_remove_cliente_tentativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='blocked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
